# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ac78b6d23c89e5af70672dcc4494e8b38f1a54fc28405a7714eb306bfda00b749a781f77fcff6a49c10eddb1cf7130ec5f9a614e953412cc6e33d71a58c33c7

test:
  secret_key_base: 23ef0420229086b695b5c576e1e90cda0774d8a9e347d11d0387a5475c692bae8e98d5541d0973b69aaca933fd416646b3a94deb57202e653a623a42f45de936

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
